version: '3'
services:
  gateway:
    image: iaross/tagger_frontend_standalone
    depends_on:
      - image-tagger-api
    volumes:
      - ./logs:/logs
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./to_be_tagged:/images/
    ports:
      - 8080:80
  image-tagger-api:
    image: iaross/tagger_api
    environment:
      # This should be changeable obviously
      - IMAGE_TAGGER_API_MODE=annotate
      - DBHOST=db
      - DBPORT=5432
    depends_on:
      - db
    volumes:
      - ./api:/debug-src
    ports:
      - 8081:5454
    command: "node index.js"
  db:
    image: mdillon/postgis:11
    volumes:
      - ./pg_data/:/var/lib/postgresql/data
      - ./init-sql:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=annotations
    ports:
      - 55432:5432
  import_data:
    image: iaross/tagger_importer
    environment:
      - DB_HOST=db
      - PG_CONN_STR=postgresql://postgres:@db:5432/annotations
      - STACK_NAME=default
      - STACK_TYPE=annotation
    volumes:
      - ./to_be_tagged:/data/
#    command: tail -f /dev/null

